services:
  - type: web
    name: miraiai-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL_NAME
        value: llama-3.3-70b-versatile
      - key: GROQ_VISION_MODEL
        value: meta-llama/llama-4-scout-17b-16e-instruct
